### ISSUE TITLE
Typescript integration

### ISSUE THREAD

**Issue by mechamocarol** [Laximas/vue3-steppy#20]
I can't find any way to use it in my application (Vue 3 and Typescript).

Could somebody help me?
I've tried to create the d.ts file, but it seems to have no effects.

<img width="735" alt="image" src="https://github.com/Laximas/vue3-steppy/assets/50451937/0a2f0b39-c313-45f3-ad69-ea20a4423d01">

**Comment by Laximas** [comment]
Hello @mechamocarol thanks for your feedback. I have added typescript support to the module, please try to install the latest version (1.5.0) and update me if it works as expected. Thanks!
