### ISSUE TITLE
Customize the size of stepper circles

### ISSUE THREAD

**Issue by jduncanRadBlue** [Laximas/vue3-steppy#5]
Hi there,
Thank you for this stepper!  Its solving what I need at the moment before vuetify comes out with version 3 of the stepper.  I was wondering if there's a way to style the size of the circles for each step?

Thanks!

**Comment by Laximas** [comment]
Hey, that is currently not possible but it’s a nice addition. I am currently on vacations but I will see what I can do when I come back

**Comment by Laximas** [comment]
I added a prop to allow changing the size of the circle. I will close this issue, you can have a look and feel free to reopen it if you need something more regarding this =) Sorry for taking so long
