### ISSUE TITLE
Button Disable Feature 

### ISSUE THREAD

**Issue by p4v3** [Laximas/vue3-steppy#6]
I would like to request the addition of an API prop to enable and disable the button disable in the Vue multistep component. The proposed API prop would empower developers to easier control the activation status of the "Next" and "Done" buttons based on specified criteria.

**Comment by Laximas** [comment]
Hey, this is already available with the "isValid" parameter of the "tabs" prop. You can pass your conditions there with a computed property even that will enable/disable the specified button accordingly

**Comment by p4v3** [comment]
okay im blind. 
Thank you very much
