### ISSUE TITLE
Next and Back Buttons submit Forms

### ISSUE THREAD

**Issue by mattsidnell** [Laximas/vue3-steppy#7]
Where a form is spanning the templates, the next and back buttons submit the form as standard.  As this can be achieved in the success function, an easy way to stop this behaviour would be to add the "type='button'" attribute to the buttons in the controls div.

**Comment by Laximas** [comment]
Thanks for the input, should be fixed now =) Will mark it as closed, feel free to reopen if you face any new issues regarding this
